-- Migration: Create mst_uom table and seed UoM data
-- Generated from Base_UoM_Definition_v1.0.xlsx
-- Date: 2026-06-10

BEGIN;

CREATE TABLE IF NOT EXISTS public.mst_uom (
    id bigserial PRIMARY KEY,
    uom_code varchar(20) NOT NULL,
    description varchar(255) NOT NULL,
    definition text,
    example text,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_mst_uom_code UNIQUE (uom_code)
);

INSERT INTO public.mst_uom (uom_code, description, definition, example) VALUES
    ('"', 'Inch', 'Satuan panjang dalam sistem imperial yang setara dengan 2,54 sentimeter', 'Diameter pipa 2"'),
    ('"2', 'Square inch', 'Satuan luas yang merupakan luas persegi dengan sisi satu inci', 'Luas gasket 10 in²'),
    ('"3', 'Cubic inch', 'Satuan volume yang merupakan volume kubus dengan sisi satu inci', 'Volume komponen 15 in³'),
    ('%', 'Percentage', 'Satuan yang menyatakan bagian per seratus (per 100)', 'Kadar air 8%'),
    ('%O', 'Per Mille', 'Satuan yang menyatakan bagian per seribu (‰)', 'Tingkat impuritas 2‰'),
    ('000', 'Meter/Minute', 'Satuan kecepatan yang menyatakan jumlah meter yang ditempuh per menit', 'Kecepatan conveyor 12 m/menit'),
    ('001', 'Unidentification', 'Unidentification', 'Unidentification'),
    ('002', 'Length in Meters per Unit', 'Satuan yang menyatakan panjang dalam meter untuk setiap satu unit', '5 meter per roll'),
    ('003', 'Unidentification', 'Unidentification', 'Unidentification'),
    ('004', 'Unidentification', 'Unidentification', 'Unidentification'),
    ('005', 'Unidentification', 'Unidentification', 'Unidentification'),
    ('006', 'Unidentification', 'Unidentification', 'Unidentification'),
    ('007', 'Unidentification', 'Unidentification', 'Unidentification'),
    ('008', 'Unidentification', 'Unidentification', 'Unidentification'),
    ('009', 'Unidentification', 'Unidentification', 'Unidentification'),
    ('010', 'Unidentification', 'Unidentification', 'Unidentification'),
    ('047', 'Unidentification', 'Unidentification', 'Unidentification'),
    ('ACR', 'Acre', 'Satuan luas dalam sistem imperial yang setara dengan ±4.046,86 meter persegi', 'Luas lahan kebun 25 acre'),
    ('B/L', 'Bill of Lading', 'Dokumen resmi pengangkutan barang yang diterbitkan oleh pihak pengangkut sebagai bukti penerimaan dan pengiriman barang', 'Pengiriman CPO dilengkapi 1 B/L'),
    ('BAG', 'Bag', 'Satuan kemasan berupa kantong atau karung', '50 bag pupuk'),
    ('BBT', 'Bibit', 'Satuan hitung untuk tanaman muda atau bibit', '1.000 bibit kelapa sawit'),
    ('BCK', 'BUCKET', 'Satuan kemasan atau wadah berbentuk ember', '5 bucket grease'),
    ('BCS', 'Bunches', 'Satuan hitung untuk tandan buah', '120 bunches TBS'),
    ('BLK', 'Block', 'Satuan area atau pembagian wilayah dalam kebun atau lokasi produksi', 'Blok A terdiri dari 15 hektar'),
    ('BOK', 'Book', 'Satuan hitung untuk buku atau dokumen tercetak', '10 book manual operasional'),
    ('BOX', 'Box', 'Satuan kemasan berupa kotak', '20 box suku cadang'),
    ('BRG', 'BAR Gauge', 'Satuan tekanan yang diukur dalam bar (gauge pressure)', 'Tekanan boiler 8 barg'),
    ('BRL', 'Barrel', 'Satuan volume berbentuk drum besar, umum digunakan untuk cairan', '10 barrel minyak'),
    ('BT', 'Bottle', 'Satuan kemasan berupa botol', '24 bottle bahan kimia'),
    ('Bqm', 'Becquerel/Cubic Meter', 'Satuan konsentrasi radioaktivitas per meter kubik', '50 Bq/m³'),
    ('C/D', 'C/D', 'Singkatan yang digunakan sesuai kebutuhan bisnis (perlu definisi internal perusahaan)', 'Digunakan sesuai konteks dokumen'),
    ('C3S', 'Cubic centimeter/second', 'Satuan laju aliran volume sebesar sentimeter kubik per detik', 'Debit aliran 30 cm³/detik'),
    ('CAL', 'Calories', 'Satuan energi yang menyatakan jumlah panas atau energi', 'Nilai energi 500 cal'),
    ('CAN', 'Canister', 'Satuan kemasan berupa tabung atau wadah tertutup', '5 canister gas'),
    ('CAR', 'Carton', 'Satuan kemasan berupa kardus besar', '15 carton produk jadi'),
    ('CAS', 'Case', 'Satuan kemasan yang terdiri dari beberapa unit dalam satu kemasan besar', '1 case berisi 24 botol'),
    ('CCM', 'Cubic centimeter', 'Satuan volume setara dengan 1 mililiter', 'Kapasitas mesin 150 cc'),
    ('CD3', 'Cubic decimeter', 'Satuan volume setara dengan 1 liter', '10 dm³ cairan'),
    ('CER', 'Certificate', 'Satuan hitung untuk dokumen sertifikat', '1 certificate mutu'),
    ('CIL', 'Coil', 'Satuan hitung untuk barang berbentuk gulungan', '3 coil kabel listrik'),
    ('CL', 'Centiliter', 'Satuan volume yang setara dengan 0,01 liter (1/100 liter)', '50 cl cairan'),
    ('CM', 'Centimeter', 'Satuan panjang yang setara dengan 1/100 meter', 'Panjang pipa 30 cm'),
    ('CM2', 'Square centimeter', 'Satuan luas yang merupakan luas persegi dengan sisi satu sentimeter', 'Luas label 25 cm²'),
    ('CMS', 'Centimeter/second', 'Satuan kecepatan yang menyatakan sentimeter per detik', 'Kecepatan aliran 5 cm/detik'),
    ('CO2', 'Carbon Dioxide Equivalent', 'Satuan yang menyatakan jumlah emisi gas rumah kaca yang dikonversi setara dengan karbon dioksida', 'Emisi 10 ton CO₂e'),
    ('CON', 'Container', 'Satuan kemasan berupa kontainer pengiriman', '2 container CPO ekspor'),
    ('CRT', 'Crate', 'Satuan kemasan berupa peti atau keranjang besar', '10 crate produk'),
    ('CYL', 'CYLINDER', 'Satuan kemasan atau tabung berbentuk silinder', '4 cylinder gas'),
    ('D', 'Days', 'Satuan waktu yang setara dengan 24 jam', 'Proses fermentasi 3 hari'),
    ('DAY', 'Days', 'Satuan waktu yang setara dengan 24 jam', 'Lead time 5 hari'),
    ('DEG', 'Degree', 'Satuan untuk menyatakan sudut atau suhu', 'Suhu 90°C'),
    ('DM', 'Decimeter', 'Satuan panjang yang setara dengan 0,1 meter', 'Panjang 5 dm'),
    ('DOC', 'Document', 'Satuan hitung untuk dokumen', '1 document kontrak'),
    ('DRM', 'Drum', 'Satuan kemasan berupa drum besar untuk cairan atau bahan kimia', '3 drum pelumas'),
    ('DZ', 'Dozen', 'Satuan jumlah yang setara dengan 12 unit', '2 dozen botol sampel'),
    ('EA', 'Each', 'Satuan dasar yang menyatakan satu item atau satuan tunggal', '1 EA spare part'),
    ('EML', 'Enzyme Units/Milliliter', 'Satuan konsentrasi aktivitas enzim per mililiter larutan', '200 EML larutan enzim'),
    ('FOZ', 'Fluid Ounce US', 'Satuan volume cairan dalam sistem US yang setara ±29,57 mililiter', '16 fl oz cairan'),
    ('FT', 'Foot', 'Satuan panjang dalam sistem imperial yang setara dengan 0,3048 meter', 'Panjang kabel 10 ft'),
    ('FT2', 'Square foot', 'Satuan luas yang merupakan luas persegi dengan sisi satu kaki', 'Luas gudang 500 ft²'),
    ('FT3', 'Cubic foot', 'Satuan volume yang merupakan volume kubus dengan sisi satu kaki', 'Kapasitas 100 ft³'),
    ('FTE', 'FULL TIME EQUIVALENT', 'Satuan yang menyatakan jumlah tenaga kerja setara penuh waktu', '10 FTE karyawan'),
    ('G', 'Gram', 'Satuan berat dalam sistem metrik yang setara dengan 1/1000 kilogram', 'Berat sampel 500 g'),
    ('G/L', 'Gram Active Ingredient/Liter', 'Satuan konsentrasi yang menyatakan jumlah gram bahan aktif dalam satu liter larutan', 'Pestisida 200 g/L'),
    ('GA', 'Unidentification', 'Unidentification', 'Unidentification'),
    ('GAI', 'Gram Active Ingredient', 'Satuan berat yang menyatakan jumlah gram bahan aktif dalam suatu produk', 'Kandungan 500 gram bahan aktif (GAI)'),
    ('GAL', 'US Gallon', 'Satuan volume dalam sistem Amerika Serikat yang setara ±3,785 liter', '100 gallon solar'),
    ('GAU', 'Gram Gold', 'Satuan berat untuk menyatakan jumlah gram emas', '5 gram emas (GAU)'),
    ('GJ', 'Gigajoule', 'Satuan energi yang setara dengan satu miliar joule (10⁹ joule)', 'Konsumsi energi 15 GJ'),
    ('GLI', 'Gram/liter', 'Satuan konsentrasi yang menyatakan jumlah gram zat dalam satu liter larutan', 'Konsentrasi pupuk 250 g/L'),
    ('GM', 'Gram/Mole', 'Satuan massa molar yang menyatakan gram per mol zat', 'Massa molar 180 g/mol'),
    ('GM2', 'Gram/square meter', 'Satuan berat per luas yang menyatakan gram per meter persegi', 'Berat kemasan 80 g/m²'),
    ('GM3', 'Gram/Cubic Meter', 'Satuan konsentrasi massa yang menyatakan gram per meter kubik', 'Konsentrasi debu 5 g/m³'),
    ('GOH', 'Gigaohm', 'Satuan hambatan listrik yang setara dengan satu miliar ohm (10⁹ ohm)', 'Resistansi 2 GOH'),
    ('GPH', 'Gallons per hour (US)', 'Satuan laju aliran volume yang menyatakan gallon per jam (US)', 'Debit pompa 50 GPH'),
    ('GPM', 'Gallons per mile (US)', 'Satuan konsumsi bahan bakar yang menyatakan gallon per mil (US)', 'Konsumsi 0,1 GPM'),
    ('GRO', 'Gross', 'Satuan jumlah yang setara dengan 144 unit (12 lusin)', '1 gross botol plastik'),
    ('H', 'Hour', 'Satuan waktu yang setara dengan 60 menit', 'Waktu proses 2 jam'),
    ('HA', 'Hectare', 'Satuan luas yang setara dengan 10000 meter persegi', 'Luas kebun 25 ha'),
    ('HK', 'Hari Kerja', 'Satuan waktu yang menyatakan satu hari kerja efektif', '5 HK untuk penyelesaian pekerjaan'),
    ('HL', 'Hectoliter', 'Satuan volume yang setara dengan 100 liter', 'Produksi 20 HL'),
    ('HR', 'Hours', 'Satuan waktu yang setara dengan 60 menit', 'Operasional 8 hours per shift'),
    ('Hm', 'Unidentification', 'Unidentification', 'Unidentification'),
    ('IBC', 'Intermediate bulk containers', 'Satuan kemasan berupa wadah besar untuk penyimpanan dan pengangkutan cairan atau bahan curah', '2 IBC bahan kimia'),
    ('JAR', 'JAR', 'Satuan kemasan berupa toples atau wadah kecil', '10 jar sampel produk'),
    ('JKG', 'Joule/Kilogram', 'Satuan energi spesifik yang menyatakan joule per kilogram', 'Nilai energi 500 J/kg'),
    ('JKK', 'Spec. Heat Capacity', 'Satuan kapasitas panas jenis yang menyatakan jumlah energi untuk menaikkan suhu 1 kg zat sebesar 1 Kelvin', 'Kapasitas panas 4200 J/kg·K'),
    ('JMO', 'Joule/Mole', 'Satuan energi per mol zat', 'Energi reaksi 250 J/mol'),
    ('JOB', 'JOB', 'Satuan hitung untuk satu pekerjaan atau aktivitas tertentu', '1 job perawatan mesin'),
    ('JRG', 'Jerrycan', 'Satuan kemasan berupa jerigen untuk cairan', '5 jerigen solar'),
    ('KAI', 'Kilogram Active Ingredient', 'Satuan berat yang menyatakan jumlah kilogram bahan aktif dalam suatu produk', 'Kandungan 2 kg bahan aktif'),
    ('KD3', 'Kilogram/cubic decimeter', 'Satuan massa jenis yang menyatakan kilogram per desimeter kubik', 'Massa jenis 0,8 kg/dm³'),
    ('KG', 'Kilogram', 'Satuan berat dalam sistem metrik yang setara dengan 1.000 gram', 'Berat pupuk 50 kg'),
    ('KGM', 'Kilogram/Mole', 'Satuan massa molar yang menyatakan kilogram per mol zat', 'Massa molar 0,018 kg/mol'),
    ('KGS', 'Kilogram/second', 'Satuan laju aliran massa yang menyatakan kilogram per detik', 'Debit uap 3 kg/detik'),
    ('KGV', 'Kilogram/cubic meter', 'Satuan massa jenis yang menyatakan kilogram per meter kubik', 'Massa jenis CPO 900 kg/m³'),
    ('KIK', 'kg Active Ingredient/kg', 'Satuan rasio yang menyatakan kilogram bahan aktif per kilogram produk', 'Konsentrasi 0,5 kg AI/kg'),
    ('KIT', 'Kit', 'Satuan kemasan atau paket yang terdiri dari beberapa item dalam satu set', '1 kit alat uji'),
    ('KJK', 'Kilojoule/kilogram', 'Satuan energi spesifik yang menyatakan kilojoule per kilogram', 'Nilai kalor 1200 kJ/kg'),
    ('KJM', 'Kilojoule/Mole', 'Satuan energi yang menyatakan kilojoule per mol zat', 'Energi reaksi 50 kJ/mol'),
    ('KL', 'Kiloliter', 'Satuan volume yang setara dengan 1.000 liter', 'Tangki 30 KL'),
    ('KM', 'Kilometer', 'Satuan panjang yang setara dengan 1.000 meter', 'Jarak 15 km'),
    ('KM2', 'Square kilometer', 'Satuan luas yang setara dengan 1.000.000 meter persegi', 'Area kebun 2 km²'),
    ('KMH', 'Kilometer/hour', 'Satuan kecepatan yang menyatakan kilometer per jam', 'Kecepatan kendaraan 60 km/jam'),
    ('KML', 'Kilomol', 'Satuan jumlah zat yang setara dengan 1.000 mol', '0,5 kmol gas'),
    ('KMN', 'Kelvin/Minute', 'Satuan laju perubahan suhu yang menyatakan Kelvin per menit', 'Kenaikan suhu 5 K/menit'),
    ('KMS', 'Kelvin/Second', 'Satuan laju perubahan suhu yang menyatakan Kelvin per detik', 'Pendinginan 2 K/detik'),
    ('KPA', 'Kilopascal', 'Satuan tekanan yang setara dengan 1.000 pascal', 'Tekanan 150 kPa'),
    ('KT', 'Kiloton', 'Satuan massa yang setara dengan 1.000 ton metrik', 'Produksi 5 kt per tahun'),
    ('KVA', 'Kilovoltampere', 'Satuan daya semu listrik yang setara dengan 1.000 voltampere', 'Kapasitas genset 250 kVA'),
    ('Km', 'Unidentification', 'Unidentification', 'Unidentification'),
    ('Kwh', 'Kilowatthour', 'Satuan energi listrik yang menyatakan penggunaan daya sebesar 1 kilowatt selama 1 jam', 'Konsumsi listrik 500 kWh'),
    ('L', 'Liter', 'Satuan volume yang setara dengan 1.000 mililiter', '200 liter solar'),
    ('LB', 'Pound', 'Satuan berat dalam sistem imperial yang setara ±0,4536 kilogram', 'Berat 100 lb'),
    ('LEN', 'LENGTH', 'Satuan yang menyatakan panjang suatu objek', 'Panjang pipa 6 meter (LEN)'),
    ('LHK', 'Liter per 100 km', 'Satuan konsumsi bahan bakar yang menyatakan jumlah liter per 100 kilometer', 'Konsumsi kendaraan 12 L/100 km'),
    ('LMI', 'Liter/Minute', 'Satuan laju aliran volume yang menyatakan liter per menit', 'Debit pompa 20 L/menit'),
    ('LMS', 'Liter/Mole Second', 'Satuan laju reaksi atau laju aliran yang menyatakan liter per mol per detik', 'Konstanta reaksi 0,5 L/mol·detik'),
    ('LOT', 'Lot', 'Satuan hitung untuk kelompok atau batch produksi tertentu', '1 lot produksi CPO'),
    ('LPH', 'Liter per hour', 'Satuan laju aliran volume yang menyatakan liter per jam', 'Konsumsi bahan bakar 50 L/jam'),
    ('LTH', 'Length', 'Satuan yang menyatakan panjang suatu material atau produk', '100 meter kabel (LTH)'),
    ('M', 'Meter', 'Satuan panjang dalam sistem metrik', 'Tinggi tangki 12 m'),
    ('M-2', '1/Square Meter', 'Satuan yang menyatakan kebalikan dari meter persegi (per m²)', '5 unit/m²'),
    ('M/H', 'Meter/Hour', 'Satuan kecepatan yang menyatakan meter per jam', 'Kecepatan conveyor 100 m/jam'),
    ('M/L', 'Mole per Liter', 'Satuan konsentrasi molar yang menyatakan mol per liter larutan', 'Konsentrasi 2 mol/L'),
    ('M/M', 'Mole per Cubic Meter', 'Satuan konsentrasi yang menyatakan mol per meter kubik', 'Konsentrasi gas 10 mol/m³'),
    ('M/S', 'Meter/second', 'Satuan kecepatan yang menyatakan meter per detik', 'Kecepatan aliran 3 m/detik'),
    ('M2', 'Square meter', 'Satuan luas yang setara dengan luas persegi sisi satu meter', 'Luas gudang 1000 m²'),
    ('M2S', 'Square meter/second', 'Satuan laju perubahan luas atau difusivitas yang menyatakan meter persegi per detik', 'Koefisien difusi 0,01 m²/detik'),
    ('M3', 'Cubic meter', 'Satuan volume yang setara dengan volume kubus sisi satu meter', 'Kapasitas tangki 50 m³'),
    ('M3D', 'Cubic meter/day', 'Satuan laju aliran volume yang menyatakan meter kubik per hari', 'Produksi limbah 200 m³/hari'),
    ('M3H', 'Cubic meter/Hour', 'Satuan laju aliran volume yang menyatakan meter kubik per jam', 'Kapasitas pompa 30 m³/jam'),
    ('M3S', 'Cubic meter/second', 'Satuan laju aliran volume yang menyatakan meter kubik per detik', 'Debit sungai 5 m³/detik'),
    ('MBT', 'MMBTU', 'Satuan energi yang setara dengan satu juta British Thermal Unit (BTU)', 'Konsumsi gas 15 MMBTU'),
    ('MCF', 'million Standard Cubic Foot', 'Satuan volume gas setara satu juta kaki kubik pada kondisi standar', 'Produksi gas 3 MCF'),
    ('MEJ', 'Megajoule', 'Satuan energi yang setara dengan satu juta joule', 'Energi boiler 25 MJ'),
    ('MG', 'Milligram', 'Satuan berat yang setara dengan 1/1.000 gram', 'Dosis bahan kimia 500 mg'),
    ('MGL', 'Milligram/liter', 'Satuan konsentrasi yang menyatakan milligram zat dalam satu liter larutan', 'Kandungan 10 mg/L'),
    ('MGO', 'Megohm', 'Satuan hambatan listrik yang setara dengan satu juta ohm', 'Resistansi 5 MΩ'),
    ('MGQ', 'Milligram/cubic meter', 'Satuan konsentrasi massa yang menyatakan milligram per meter kubik', 'Kadar debu 3 mg/m³'),
    ('MHV', 'Megavolt', 'Satuan tegangan listrik yang setara dengan satu juta volt', 'Tegangan 2 MV'),
    ('MI', 'Mile', 'Satuan panjang dalam sistem imperial yang setara ±1,609 kilometer', 'Jarak 5 mile'),
    ('MI2', 'Square Mile', 'Satuan luas dalam sistem imperial setara satu mil persegi', 'Area 2 mi²'),
    ('MIN', 'Minute', 'Satuan waktu yang setara dengan 60 detik', 'Waktu proses 30 menit'),
    ('MIS', 'Microsecond', 'Satuan waktu yang setara dengan 1/1.000.000 detik', 'Delay 5 µs'),
    ('ML', 'Milliliter', 'Satuan volume yang setara dengan 1/1.000 liter', '250 ml sampel'),
    ('MLI', 'Milliliter Active Ingredient', 'Satuan volume yang menyatakan jumlah mililiter bahan aktif dalam suatu produk', '20 ml bahan aktif'),
    ('MM', 'Millimeter', 'Satuan panjang yang setara dengan 1/1.000 meter', 'Tebal plat 5 mm'),
    ('MM2', 'Square millimeter', 'Satuan luas yang merupakan milimeter persegi', 'Penampang 10 mm²'),
    ('MM3', 'Cubic millimeter', 'Satuan volume yang merupakan milimeter kubik', 'Volume 50 mm³'),
    ('MN', 'Meganewton', 'Satuan gaya yang setara dengan satu juta newton', 'Beban tekan 2 MN'),
    ('MNM', 'Millinewton/meter', 'Satuan gaya per panjang yang menyatakan millinewton per meter', 'Tegangan 5 mN/m'),
    ('MON', 'Months', 'Satuan waktu dalam bulan', 'Kontrak 12 bulan'),
    ('MPG', 'Miles per gallon (US)', 'Satuan efisiensi bahan bakar yang menyatakan mil per gallon (US)', 'Konsumsi 25 MPG'),
    ('MPL', 'Millimole per Liter', 'Satuan konsentrasi yang menyatakan millimol per liter larutan', 'Konsentrasi 5 mmol/L'),
    ('MPS', 'Millipascal seconds', 'Satuan viskositas dinamis yang menyatakan millipascal detik', 'Viskositas 10 mPa·s'),
    ('MS2', 'Meter/Square Second', 'Satuan percepatan yang menyatakan meter per detik kuadrat', 'Percepatan 9,81 m/s²'),
    ('MSC', 'Microsiemens per centimeter', 'Satuan konduktivitas listrik yang menyatakan mikrosiemens per sentimeter', 'Konduktivitas 250 µS/cm'),
    ('MSE', 'Millisecond', 'Satuan waktu yang setara dengan 1/1.000 detik', 'Delay sistem 50 ms'),
    ('MT', 'Metric Tonne', 'Satuan berat yang setara dengan 1.000 kilogram', 'Produksi 25 MT CPO'),
    ('MVA', 'Megavoltampere', 'Satuan daya semu listrik yang setara dengan satu juta voltampere', 'Kapasitas trafo 30 MVA'),
    ('MWH', 'Megawatt hour', 'Satuan energi listrik yang setara dengan 1.000 kilowatt jam', 'Konsumsi 5 MWh'),
    ('NA', 'Nanoampere', 'Satuan arus listrik yang setara 10⁻⁹ ampere', 'Arus 25 nA'),
    ('NAM', 'Nanometer', 'Satuan panjang yang setara 10⁻⁹ meter', 'Panjang gelombang 500 nm'),
    ('NI', 'Kilonewton', 'Satuan gaya yang setara dengan 1.000 newton', 'Beban 50 kN'),
    ('NM', 'Newton/meter', 'Satuan torsi atau konstanta pegas', 'Torsi 20 Nm'),
    ('NM3', 'Normal Cubic meter', 'Satuan volume gas pada kondisi normal (suhu dan tekanan standar)', '200 Nm³ gas'),
    ('NMM', 'Newton/Square Millimeter', 'Satuan tekanan atau tegangan yang menyatakan newton per mm²', 'Tegangan 5 N/mm²'),
    ('NS', 'Nanosecond', 'Satuan waktu yang setara 10⁻⁹ detik', '10 ns'),
    ('NUM', 'NUMBER', 'Satuan hitung jumlah item atau dokumen', '5 number dokumen'),
    ('OCM', 'Specific Electrical Resistance', 'Satuan hambatan jenis listrik suatu material', 'Resistivitas 1 OCM'),
    ('OM', 'Specific Electrical Resistance', 'Satuan hambatan jenis listrik (umumnya dalam ohm-meter)', 'Resistivitas 0,02 Ω·m'),
    ('OZ', 'Ounce', 'Satuan berat dalam sistem imperial setara ±28,35 gram', '12 oz produk'),
    ('P', 'Points', 'Satuan nilai atau skor tertentu sesuai kebutuhan bisnis', '10 points evaluasi'),
    ('PAA', 'Pair', 'Satuan jumlah yang setara dengan dua unit', '1 pasang sepatu safety'),
    ('PAC', 'Pack', 'Satuan kemasan berupa pak', '1 pack suku cadang'),
    ('PAD', 'PAD', 'Satuan lembaran atau bantalan', '5 pad filter'),
    ('PAI', 'Pail', 'Satuan kemasan berupa ember atau wadah plastik', '3 pail cat'),
    ('PAL', 'Pallet', 'Satuan kemasan berupa palet untuk pengiriman', '10 pallet produk'),
    ('PAR', 'PAIL', 'Satuan kemasan berupa ember (serupa PAI)', '2 pail bahan kimia'),
    ('PAS', 'Pascal second', 'Satuan viskositas dinamis (Pa·s)', 'Viskositas 0,5 Pa·s'),
    ('PC', 'PIECE', 'Satuan hitung per satu buah/barang', '1 pc spare part'),
    ('PCH', 'POUCH', 'Satuan kemasan berupa kantong kecil', '50 pouch sampel'),
    ('PDA', 'Consultant Days', 'Satuan hari kerja konsultan', '3 consultant days'),
    ('PF', 'Pikofarad', 'Satuan kapasitansi listrik setara 10⁻¹² farad', 'Kapasitansi 10 pF'),
    ('PKK', 'Pokok', 'Satuan hitung jumlah pohon atau tanaman pokok (konteks perkebunan)', '1000 pokok sawit'),
    ('PMI', '1/minute', 'Satuan frekuensi atau laju kejadian per menit', '20 siklus/menit'),
    ('PMR', 'Permeation Rate SI', 'Satuan laju perembesan sesuai standar SI', '5 PMR'),
    ('POL', 'Pole', 'Satuan tiang atau kutub', '20 pole listrik'),
    ('PPB', 'Parts per billion', 'Satuan konsentrasi bagian per miliar', '2 ppb'),
    ('PPM', 'Parts per million', 'Satuan konsentrasi bagian per sejuta', '50 ppm'),
    ('PPT', 'Parts per trillion', 'Satuan konsentrasi bagian per triliun', '0,5 ppt'),
    ('PRC', 'Group proportion', 'Satuan proporsi kelompok dalam persentase atau rasio', 'Proporsi 0,8 PRC'),
    ('PRM', 'Permeation Rate', 'Satuan laju perembesan suatu zat', '3 PRM'),
    ('PRS', 'Number of Persons', 'Satuan jumlah orang', '10 persons'),
    ('PS', 'Picosecond', 'Satuan waktu setara 10⁻¹² detik', '5 ps'),
    ('PT', 'Pint, US liquid', 'Satuan volume cair sistem US setara ±0,473 liter', '2 pint'),
    ('PU', 'Activity unit', 'Satuan aktivitas enzim atau zat biologis', '100 PU'),
    ('QT', 'Quart, US liquid', 'Satuan volume cair sistem US setara ±0,946 liter', '4 quart'),
    ('R-U', 'Nanofarad', 'Satuan kapasitansi listrik setara 10⁻⁹ farad', '50 nF'),
    ('RAC', 'Rack', 'Satuan penyimpanan berupa rak atau susunan bertingkat', '2 rack barang jadi'),
    ('REM', 'Ream', 'Satuan jumlah kertas yang umumnya terdiri dari 500 lembar', '1 ream kertas A4'),
    ('RF', 'Millifarad', 'Satuan kapasitansi listrik setara 10⁻³ farad', 'Kapasitansi 5 mF'),
    ('RHO', 'Gram/Cubic Centimeter', 'Satuan massa jenis yang menyatakan gram per sentimeter kubik', 'Massa jenis 0,92 g/cm³'),
    ('RIM', 'Rim', 'Satuan jumlah atau unit tertentu sesuai kebutuhan bisnis (umumnya velg roda)', '4 rim roda'),
    ('RIT', 'RITASE', 'Satuan jumlah perjalanan pengangkutan (rit)', '3 rit pengiriman TBS'),
    ('RLL', 'Roll', 'Satuan kemasan berbentuk gulungan', '5 roll plastik'),
    ('ROL', 'Roll', 'Satuan kemasan berbentuk gulungan', '2 roll kabel'),
    ('RUN', 'Run', 'Satuan aktivitas atau siklus operasi tertentu', '1 run produksi'),
    ('RXN', 'Reaction', 'Satuan jumlah reaksi atau proses reaksi', '1 reaction batch'),
    ('S/M', 'Siemens per meter', 'Satuan konduktivitas listrik dalam sistem SI', '5 S/m'),
    ('SAK', 'Sack', 'Satuan kemasan berupa karung besar', '50 sack pupuk'),
    ('SCH', 'Sachet', 'Satuan kemasan kecil sekali pakai', '100 sachet produk'),
    ('SET', 'Set', 'Satuan paket yang terdiri dari beberapa item', '1 set alat uji'),
    ('SHF', 'Shifting', 'Satuan jumlah perpindahan atau pergeseran (shift)', '3 shifting kerja'),
    ('SHT', 'Sheet', 'Satuan lembar', '20 sheet dokumen'),
    ('SPL', 'Sample', 'Satuan sampel untuk pengujian atau analisa', '1 sample CPO'),
    ('ST', 'items', 'Satuan hitung barang atau item', '10 items suku cadang'),
    ('STK', 'Stick', 'Satuan batang atau stik', '20 stick elektroda'),
    ('TIN', 'Tin', 'Satuan kemasan kaleng', '12 tin cat'),
    ('TNK', 'Tank', 'Satuan wadah tangki penyimpanan', '1 tank CPO'),
    ('TO', 'Ton', 'Satuan berat ton (umum, perlu klarifikasi sistem metrik/US)', '5 ton bahan baku'),
    ('TOM', 'Ton/Cubic Meter', 'Satuan massa jenis yang menyatakan ton per meter kubik', '0,9 ton/m³'),
    ('TON', 'US Ton', 'Satuan berat dalam sistem US setara ±907 kilogram', '10 US ton'),
    ('TP', 'Trip', 'Satuan perjalanan pengangkutan', '3 trip truk'),
    ('TRK', 'Truck', 'Satuan pengiriman per truk', '2 truck TBS'),
    ('TRP', 'Trip', 'Satuan perjalanan pengangkutan', '5 trip pengiriman'),
    ('TRY', 'Tray', 'Satuan kemasan berupa nampan', '4 tray produk'),
    ('TS', 'Thousands', 'Satuan ribuan unit', '5 TS bibit sawit'),
    ('TU', 'TUB', 'Satuan kemasan berupa wadah atau bak kecil', '3 tub grease'),
    ('TUB', 'Tube', 'Satuan kemasan tabung kecil', '10 tube lem'),
    ('UE', 'Enzyme Units', 'Satuan aktivitas enzim', '200 UE'),
    ('UN', 'Unit', 'Satuan dasar satuan tunggal', '1 unit mesin'),
    ('VAI', 'Vail', 'Satuan kemasan tertentu sesuai definisi internal perusahaan', '1 vail bahan kimia'),
    ('VAL', 'Value-Only Material', 'Satuan untuk material yang hanya memiliki nilai finansial tanpa kuantitas fisik', 'Material jasa 1 VAL'),
    ('VAM', 'Voltampere', 'Satuan daya semu listrik', '500 VA'),
    ('VIS', 'VISS', 'Satuan berat tradisional (umumnya di Myanmar) ±1,63 kg', '10 viss'),
    ('VOY', 'Voyage', 'Satuan perjalanan kapal', '1 voyage ekspor CPO'),
    ('VSL', 'Vessel', 'Satuan kapal atau tangki kapal pengangkut', '1 vessel CPO'),
    ('WK', 'Weeks', 'Satuan waktu minggu', '4 minggu proyek'),
    ('WKY', 'Evaporation Rate', 'Satuan laju penguapan sesuai standar tertentu', '2 WKY'),
    ('WMK', 'Heat Conductivity', 'Satuan konduktivitas panas (W/m·K)', '0,6 W/m·K'),
    ('YD', 'Yards', 'Satuan panjang imperial ±0,914 meter', '20 yard kain'),
    ('YD2', 'Square Yard', 'Satuan luas yard persegi', '50 yd²'),
    ('YD3', 'Cubic yard', 'Satuan volume yard kubik', '15 yd³'),
    ('YR', 'Years', 'Satuan waktu tahun', 'Kontrak 5 tahun'),
    ('dBA', 'Decibels (A Weighting)', 'Satuan tingkat kebisingan dengan pembobotan A (mendekati sensitivitas telinga manusia)', '85 dBA'),
    ('dBC', 'Decibels (C Weighting)', 'Satuan tingkat kebisingan dengan pembobotan C (untuk kebisingan frekuensi rendah)', '95 dBC'),
    ('kgb', 'Kilogram per US Barrel', 'Satuan massa dalam kilogram untuk setiap 1 US barrel (bbl) Digunakan untuk menyatakan rasio berat terhadap volume barrel standar US', 'Konsumsi aditif 8 kgb untuk setiap 1 barrel CPO'),
    ('lhh', 'US Pound per Horsepower-Hour', 'Satuan massa (pound) per satuan energi kerja mesin (horsepower-hour) Umumnya untuk efisiensi bahan bakar mesin', 'Konsumsi bahan bakar genset 05 lhh'),
    ('lht', 'US Pound per 100,000 Horsepower-Hour', 'Satuan massa dalam pound per 100.000 horsepower-hour Biasanya untuk pengukuran skala besar emisi atau konsumsi', 'Emisi boiler tercatat 3 lht'),
    ('lth', 'US Pound per 1,000 Horsepower-Hours', 'Satuan massa dalam pound per 1.000 horsepower-hour Digunakan dalam analisa performa mesin', 'Pelumas turbin 18 lth'),
    ('m3', 'Cubic Meter (Meter Kubik)', 'Satuan volume dalam sistem metrik yang setara dengan volume kubus sisi 1 meter', 'Kapasitas tangki 25 m3'),
    ('µA', 'Microampere', 'Satuan arus listrik sebesar 1 per satu juta ampere (10⁻⁶ A)', 'Output sensor 15 µA'),
    ('µF', 'Microfarad', 'Satuan kapasitansi listrik sebesar 1 per satu juta farad (10⁻⁶ F)', 'Kapasitor panel 22 µF'),
    ('µGL', 'Microgram per Liter', 'Satuan konsentrasi massa dalam mikogram per liter larutan', 'Kandungan Fe dalam air 5 µGL'),
    ('µGQ', 'Microgram per Cubic Meter', 'Satuan konsentrasi massa dalam mikogram per meter kubik udara atau gas', 'Konsentrasi debu 40 µGQ'),
    ('µL', 'Microliter', 'Satuan volume sebesar 1 per satu juta liter (10⁻⁶ L)', 'Pengambilan sampel 250 µL'),
    ('µM', 'Micrometer', 'Satuan panjang sebesar 1 per satu juta meter (10⁻⁶ m)', 'Ketebalan coating 80 µM');

COMMIT;
