const REQUEST_FIELD_RULES = [
    {
        fieldKey: "material_number",
        sectionName: "PRODUCT",
        fieldLabel: "Material",
        displayOrder: 1,
        isRequired: false,
        isLocked: true,
        defaultValue: null,
        sourceType: "SYSTEM",
        sourceReference: "SAP_MATERIAL_NUMBER",
        notes: "Tidak dapat diubah",
    },
    {
        fieldKey: "industry_sector",
        sectionName: "PRODUCT",
        fieldLabel: "Industry Sector",
        displayOrder: 2,
        isRequired: true,
        isLocked: true,
        defaultValue: "C - CHEMICAL INDUSTRY",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Default "C - Chemical Industry" dan tidak dapat diubah',
    },
    {
        fieldKey: "material_type",
        sectionName: "PRODUCT",
        fieldLabel: "Material Type",
        displayOrder: 3,
        isRequired: true,
        isLocked: false,
        defaultValue: null,
        sourceType: "USER_INPUT",
        sourceReference: null,
        notes: "Ditentukan pengguna",
    },
    {
        fieldKey: "language",
        sectionName: "PRODUCT_DESCRIPTION",
        fieldLabel: "Language",
        displayOrder: 4,
        isRequired: true,
        isLocked: true,
        defaultValue: "EN",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Default "EN" dan tidak dapat diubah',
    },
    {
        fieldKey: "material_description",
        sectionName: "PRODUCT_DESCRIPTION",
        fieldLabel: "Material Description",
        displayOrder: 5,
        isRequired: true,
        isLocked: true,
        defaultValue: null,
        sourceType: "COMPUTED_TEMPLATE",
        sourceReference: "MAT_TEMPLATE",
        notes: "Wajib diisi, maksimal 40 karakter, auto uppercase",
    },
    {
        fieldKey: "purchase_order_text",
        sectionName: "PRODUCT_DESCRIPTION",
        fieldLabel: "Purchase Order Text",
        displayOrder: 6,
        isRequired: false,
        isLocked: false,
        defaultValue: null,
        sourceType: "USER_INPUT",
        sourceReference: null,
        notes: "Optional; tidak diisi otomatis dari Material Description",
    },
    {
        fieldKey: "material_group",
        sectionName: "BASIC_DATA",
        fieldLabel: "Material Group",
        displayOrder: 7,
        isRequired: true,
        isLocked: false,
        defaultValue: null,
        sourceType: "USER_INPUT",
        sourceReference: "MAT_ITEM_GROUP",
        notes: "Wajib diisi dan ditentukan pengguna",
    },
    {
        fieldKey: "old_material_number",
        sectionName: "BASIC_DATA",
        fieldLabel: "Old Material Number",
        displayOrder: 8,
        isRequired: false,
        isLocked: false,
        defaultValue: null,
        sourceType: "USER_INPUT",
        sourceReference: null,
        notes: "Optional diisi dan maksimal 18 karakter ",
    },
    {
        fieldKey: "division",
        sectionName: "BASIC_DATA",
        fieldLabel: "Division",
        displayOrder: 9,
        isRequired: true,
        isLocked: true,
        defaultValue: "90",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Default "90" dan tidak dapat diubah',
    },
    {
        fieldKey: "base_unit_of_measure",
        sectionName: "BASIC_DATA",
        fieldLabel: "Base Unit of Measure",
        displayOrder: 10,
        isRequired: true,
        isLocked: false,
        defaultValue: null,
        sourceType: "USER_INPUT",
        sourceReference: "SAP_BASE_UOM",
        notes: "Wajib diisi dan ditentukan pengguna",
    },
    {
        fieldKey: "plant",
        sectionName: "PLANT_DATA",
        fieldLabel: "Plant",
        displayOrder: 11,
        isRequired: true,
        isLocked: false,
        defaultValue: null,
        sourceType: "USER_INPUT",
        sourceReference: "SAP_PLANT_MASTER",
        notes: "Wajib diisi dan ditentukan pengguna",
    },
    {
        fieldKey: "availability_check",
        sectionName: "PLANT_DATA",
        fieldLabel: "Availability Check",
        displayOrder: 12,
        isRequired: true,
        isLocked: true,
        defaultValue: "20",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Default "20" dan tidak dapat diubah',
    },
    {
        fieldKey: "batch_management",
        sectionName: "PLANT_DATA",
        fieldLabel: "Batch Management",
        displayOrder: 13,
        isRequired: true,
        isLocked: false,
        defaultValue: "true",
        sourceType: "BOOLEAN_FLAG",
        sourceReference: null,
        notes: "Wajib dicentang",
    },
    {
        fieldKey: "batch_management_plant",
        sectionName: "PLANT_DATA",
        fieldLabel: "Batch Management (Plant)",
        displayOrder: 14,
        isRequired: true,
        isLocked: false,
        defaultValue: "true",
        sourceType: "BOOLEAN_FLAG",
        sourceReference: null,
        notes: "Wajib dicentang",
    },
    {
        fieldKey: "transportation_group",
        sectionName: "PLANT_DATA",
        fieldLabel: "Transportation Group",
        displayOrder: 15,
        isRequired: true,
        isLocked: true,
        defaultValue: "3000",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Default "3000" dan tidak dapat diubah',
    },
    {
        fieldKey: "loading_group",
        sectionName: "PLANT_DATA",
        fieldLabel: "Loading Group",
        displayOrder: 16,
        isRequired: true,
        isLocked: true,
        defaultValue: "1000",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Default "1000" dan tidak dapat diubah',
    },
    {
        fieldKey: "mrp_type",
        sectionName: "PLANT_DATA",
        fieldLabel: "MRP Type",
        displayOrder: 17,
        isRequired: true,
        isLocked: true,
        defaultValue: "ND",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Default "ND" dan tidak dapat diubah',
    },
    {
        fieldKey: "profit_center",
        sectionName: "PLANT_DATA",
        fieldLabel: "Profit Center",
        displayOrder: 18,
        isRequired: true,
        isLocked: false,
        defaultValue: null,
        sourceType: "PLANT_FILTER",
        sourceReference: "SAP_PROFIT_CENTER_BY_PLANT",
        notes: "Value di filter berdasarkan kode Plant",
    },
    {
        fieldKey: "storage_location",
        sectionName: "PLANT_DATA",
        fieldLabel: "Storage Location",
        displayOrder: 19,
        isRequired: true,
        isLocked: false,
        defaultValue: null,
        sourceType: "PLANT_FILTER",
        sourceReference: "SAP_STORAGE_LOCATION_BY_PLANT",
        notes: "Value di filter berdasarkan kode Plant",
    },
    {
        fieldKey: "sales_organization",
        sectionName: "SALES_DATA",
        fieldLabel: "Sales Organization",
        displayOrder: 20,
        isRequired: true,
        isLocked: false,
        defaultValue: null,
        sourceType: "PLANT_FILTER",
        sourceReference: "SAP_SALES_ORG_BY_PLANT",
        notes: "Value di filter berdasarkan kode Plant",
    },
    {
        fieldKey: "distribution_channel",
        sectionName: "SALES_DATA",
        fieldLabel: "Distribution Channel",
        displayOrder: 21,
        isRequired: true,
        isLocked: false,
        defaultValue: null,
        sourceType: "PLANT_FILTER",
        sourceReference: "SAP_DISTRIBUTION_CHANNEL_BY_PLANT",
        notes: "Value di filter berdasarkan kode Plant",
    },
    {
        fieldKey: "acct_assmt_group_mat",
        sectionName: "SALES_DATA",
        fieldLabel: "Acct Assmt Group Mat.",
        displayOrder: 22,
        isRequired: true,
        isLocked: true,
        defaultValue: "20",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Default "20" dan tidak dapat diubah',
    },
    {
        fieldKey: "item_category_group",
        sectionName: "SALES_DATA",
        fieldLabel: "Item Category Group",
        displayOrder: 23,
        isRequired: true,
        isLocked: true,
        defaultValue: "NORM",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Default "NORM" dan tidak dapat diubah',
    },
    {
        fieldKey: "valuation_category",
        sectionName: "ACCOUNTING",
        fieldLabel: "Valuation Category",
        displayOrder: 24,
        isRequired: true,
        isLocked: true,
        defaultValue: "X",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Default "X" dan tidak dapat diubah',
    },
    {
        fieldKey: "price_determination_control",
        sectionName: "ACCOUNTING",
        fieldLabel: "Price Determination Control",
        displayOrder: 25,
        isRequired: true,
        isLocked: true,
        defaultValue: "2",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Default "2" dan tidak dapat diubah',
    },
    {
        fieldKey: "valuation_class",
        sectionName: "ACCOUNTING",
        fieldLabel: "Valuation Class",
        displayOrder: 26,
        isRequired: true,
        isLocked: false,
        defaultValue: null,
        sourceType: "MATERIAL_GROUP_FILTER",
        sourceReference: "SAP_VALUATION_CLASS_BY_GROUP",
        notes: "Value di filter berdasarkan kode material group",
    },
    {
        fieldKey: "valuation_class_project_stock",
        sectionName: "ACCOUNTING",
        fieldLabel: "Valuation Class for Project Stock",
        displayOrder: 27,
        isRequired: true,
        isLocked: false,
        defaultValue: null,
        sourceType: "MATERIAL_GROUP_FILTER",
        sourceReference: "SAP_VALUATION_CLASS_PROJECT_BY_GROUP",
        notes: "Value di filter berdasarkan kode material group",
    },
    {
        fieldKey: "price_control",
        sectionName: "ACCOUNTING",
        fieldLabel: "Price Control",
        displayOrder: 28,
        isRequired: true,
        isLocked: true,
        defaultValue: "V",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Default "V" dan tidak dapat diubah',
    },
    {
        fieldKey: "moving_price",
        sectionName: "ACCOUNTING",
        fieldLabel: "Moving Price",
        displayOrder: 29,
        isRequired: true,
        isLocked: true,
        defaultValue: "1",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Default "1" dan tidak dapat diubah',
    },
    {
        fieldKey: "departure_country_line_1",
        sectionName: "TAX_DATA",
        fieldLabel: "Departure Country Line 1",
        displayOrder: 30,
        isRequired: true,
        isLocked: true,
        defaultValue: "ID",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Line 1 default "ID" dan tidak dapat diubah',
    },
    {
        fieldKey: "departure_country_line_2",
        sectionName: "TAX_DATA",
        fieldLabel: "Departure Country Line 2",
        displayOrder: 31,
        isRequired: true,
        isLocked: true,
        defaultValue: "ID",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Line 2 default "ID" dan tidak dapat diubah',
    },
    {
        fieldKey: "tax_category_line_1",
        sectionName: "TAX_DATA",
        fieldLabel: "Tax Category Line 1",
        displayOrder: 32,
        isRequired: true,
        isLocked: true,
        defaultValue: "MWST",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Line 1 default "MWST" dan tidak dapat diubah',
    },
    {
        fieldKey: "tax_category_line_2",
        sectionName: "TAX_DATA",
        fieldLabel: "Tax Category Line 2",
        displayOrder: 33,
        isRequired: true,
        isLocked: true,
        defaultValue: "ZMWS",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Line 2 default "ZMWS" dan tidak dapat diubah',
    },
    {
        fieldKey: "tax_classification_line_1",
        sectionName: "TAX_DATA",
        fieldLabel: "Tax Classification Line 1",
        displayOrder: 34,
        isRequired: true,
        isLocked: true,
        defaultValue: "1 - FULL TAX",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Line 1 default "1 - Full Tax" dan tidak dapat diubah',
    },
    {
        fieldKey: "tax_classification_line_2",
        sectionName: "TAX_DATA",
        fieldLabel: "Tax Classification Line 2",
        displayOrder: 35,
        isRequired: true,
        isLocked: true,
        defaultValue: "0 - NO TAX",
        sourceType: "STATIC_DEFAULT",
        sourceReference: null,
        notes: 'Line 2 default "0 - No Tax" dan tidak dapat diubah',
    },
];

const TEMPLATE_FIELDS = [
    { fieldCode: "101", fieldKey: "part_number", fieldNameId: "PART NUMBER", dataType: "ALPHANUMERIC" },
    { fieldCode: "102", fieldKey: "material_name", fieldNameId: "MATERIAL NAME", dataType: "TEXT" },
    { fieldCode: "103", fieldKey: "type_bentuk", fieldNameId: "TYPE / BENTUK", dataType: "ALPHANUMERIC" },
    { fieldCode: "104", fieldKey: "size_dimension", fieldNameId: "SIZE / DIMENSION", dataType: "MIXED" },
    { fieldCode: "105", fieldKey: "material_spec_bahan", fieldNameId: "MATERIAL SPEC / BAHAN", dataType: "TEXT" },
    { fieldCode: "106", fieldKey: "model", fieldNameId: "MODEL", dataType: "TEXT" },
    { fieldCode: "107", fieldKey: "brand_merek", fieldNameId: "BRAND / MEREK", dataType: "TEXT" },
    { fieldCode: "108", fieldKey: "phase", fieldNameId: "PHASE", dataType: "NUMERIC" },
    { fieldCode: "109", fieldKey: "ampere", fieldNameId: "AMPERE", dataType: "NUMERIC" },
    { fieldCode: "110", fieldKey: "volt", fieldNameId: "VOLT", dataType: "NUMERIC" },
    { fieldCode: "111", fieldKey: "hz", fieldNameId: "HZ", dataType: "NUMERIC" },
    { fieldCode: "112", fieldKey: "range", fieldNameId: "RANGE", dataType: "TEXT" },
    { fieldCode: "113", fieldKey: "capacity", fieldNameId: "CAPACITY", dataType: "MIXED" },
    { fieldCode: "114", fieldKey: "power", fieldNameId: "POWER", dataType: "MIXED" },
    { fieldCode: "115", fieldKey: "speed", fieldNameId: "SPEED", dataType: "MIXED" },
    { fieldCode: "116", fieldKey: "pressure", fieldNameId: "PRESSURE", dataType: "MIXED" },
    { fieldCode: "117", fieldKey: "standard", fieldNameId: "STANDARD", dataType: "ALPHANUMERIC" },
    { fieldCode: "118", fieldKey: "specification", fieldNameId: "SPECIFICATION", dataType: "ALPHANUMERIC" },
    { fieldCode: "119", fieldKey: "grade", fieldNameId: "GRADE", dataType: "TEXT" },
    { fieldCode: "120", fieldKey: "dimension", fieldNameId: "DIMENSION", dataType: "MIXED" },
    { fieldCode: "121", fieldKey: "thickness", fieldNameId: "THICKNESS", dataType: "NUMERIC" },
    { fieldCode: "122", fieldKey: "vehicle_type", fieldNameId: "VEHICLE TYPE", dataType: "TEXT" },
    { fieldCode: "123", fieldKey: "year", fieldNameId: "YEAR", dataType: "NUMERIC" },
];

const TEMPLATE_DEFINITIONS = [
    {
        templateCode: "MECHANICAL_COMPONENT",
        templateName: "Mechanical Component",
        materialGroupCodes: ["905", "907", "911", "917", "925", "932", "950", "957", "968", "940", "955"],
        fields: [
            { fieldCode: "101", fieldOrder: 1, isMandatory: true, validationRuleType: "PREFIX", prefixValue: "P/N", ruleDetail: 'Diawali "P/N"', maxLength: null },
            { fieldCode: "102", fieldOrder: 2, isMandatory: true, validationRuleType: "CAPITAL_NO_SPECIAL_CHARS", prefixValue: null, ruleDetail: "Huruf kapital, tanpa tanda baca khusus", maxLength: null },
            { fieldCode: "103", fieldOrder: 3, isMandatory: true, validationRuleType: "ALPHANUMERIC_CAPITAL", prefixValue: null, ruleDetail: "Huruf kapital dan angka", maxLength: null },
            { fieldCode: "104", fieldOrder: 4, isMandatory: false, validationRuleType: "NONE", prefixValue: null, ruleDetail: "Tidak ada ketentuan input", maxLength: null },
            { fieldCode: "105", fieldOrder: 5, isMandatory: false, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "106", fieldOrder: 6, isMandatory: false, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "107", fieldOrder: 7, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
        ],
    },
    {
        templateCode: "ELECTRICAL_COMPONENT",
        templateName: "Electrical Component",
        materialGroupCodes: ["909", "920", "921", "947", "953", "944", "915"],
        fields: [
            { fieldCode: "101", fieldOrder: 1, isMandatory: true, validationRuleType: "PREFIX", prefixValue: "P/N", ruleDetail: 'Diawali "P/N"', maxLength: null },
            { fieldCode: "102", fieldOrder: 2, isMandatory: true, validationRuleType: "CAPITAL_NO_SPECIAL_CHARS", prefixValue: null, ruleDetail: "Huruf kapital, tanpa tanda baca khusus", maxLength: null },
            { fieldCode: "103", fieldOrder: 3, isMandatory: true, validationRuleType: "ALPHANUMERIC_CAPITAL", prefixValue: null, ruleDetail: "Huruf kapital dan angka", maxLength: null },
            { fieldCode: "104", fieldOrder: 4, isMandatory: false, validationRuleType: "NONE", prefixValue: null, ruleDetail: "Tidak ada ketentuan input", maxLength: null },
            { fieldCode: "108", fieldOrder: 5, isMandatory: false, validationRuleType: "NONE", prefixValue: null, ruleDetail: "Tidak ada ketentuan input", maxLength: null },
            { fieldCode: "109", fieldOrder: 6, isMandatory: false, validationRuleType: "NONE", prefixValue: null, ruleDetail: "Tidak ada ketentuan input", maxLength: null },
            { fieldCode: "110", fieldOrder: 7, isMandatory: false, validationRuleType: "NONE", prefixValue: null, ruleDetail: "Tidak ada ketentuan input", maxLength: null },
            { fieldCode: "111", fieldOrder: 8, isMandatory: false, validationRuleType: "NONE", prefixValue: null, ruleDetail: "Tidak ada ketentuan input", maxLength: null },
            { fieldCode: "112", fieldOrder: 9, isMandatory: false, validationRuleType: "NONE", prefixValue: null, ruleDetail: "Tidak ada ketentuan input", maxLength: null },
            { fieldCode: "106", fieldOrder: 10, isMandatory: false, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "107", fieldOrder: 11, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
        ],
    },
    {
        templateCode: "EQUIPMENT_MACHINERY",
        templateName: "Equipment / Machinery",
        materialGroupCodes: ["903", "904", "902", "906", "913", "916", "927", "935", "936", "937", "938", "969", "941", "982", "946", "971"],
        fields: [
            { fieldCode: "101", fieldOrder: 1, isMandatory: true, validationRuleType: "PREFIX", prefixValue: "P/N|POS", ruleDetail: 'Diawali "P/N" atau "POS"', maxLength: null },
            { fieldCode: "102", fieldOrder: 2, isMandatory: true, validationRuleType: "CAPITAL_NO_SPECIAL_CHARS", prefixValue: null, ruleDetail: "Huruf kapital, tanpa tanda baca khusus", maxLength: null },
            { fieldCode: "103", fieldOrder: 3, isMandatory: true, validationRuleType: "ALPHANUMERIC_CAPITAL", prefixValue: null, ruleDetail: "Huruf kapital dan angka", maxLength: null },
            { fieldCode: "113", fieldOrder: 4, isMandatory: false, validationRuleType: "NONE", prefixValue: null, ruleDetail: "Tidak ada ketentuan input", maxLength: null },
            { fieldCode: "114", fieldOrder: 5, isMandatory: false, validationRuleType: "NONE", prefixValue: null, ruleDetail: "Tidak ada ketentuan input", maxLength: null },
            { fieldCode: "115", fieldOrder: 6, isMandatory: false, validationRuleType: "NONE", prefixValue: null, ruleDetail: "Tidak ada ketentuan input", maxLength: null },
            { fieldCode: "106", fieldOrder: 7, isMandatory: false, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "107", fieldOrder: 8, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
        ],
    },
    {
        templateCode: "PROCESS_PLANT_EQUIPMENT",
        templateName: "Process / Plant Equipment",
        materialGroupCodes: ["928", "954", "973", "984", "960", "918", "943", "942", "961"],
        fields: [
            { fieldCode: "102", fieldOrder: 1, isMandatory: true, validationRuleType: "CAPITAL_NO_SPECIAL_CHARS", prefixValue: null, ruleDetail: "Huruf kapital, tanpa tanda baca khusus", maxLength: null },
            { fieldCode: "103", fieldOrder: 2, isMandatory: true, validationRuleType: "ALPHANUMERIC_CAPITAL", prefixValue: null, ruleDetail: "Huruf kapital dan angka", maxLength: null },
            { fieldCode: "113", fieldOrder: 3, isMandatory: false, validationRuleType: "NONE", prefixValue: null, ruleDetail: "Tidak ada ketentuan input", maxLength: null },
            { fieldCode: "105", fieldOrder: 4, isMandatory: false, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "106", fieldOrder: 5, isMandatory: false, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "107", fieldOrder: 6, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
        ],
    },
    {
        templateCode: "PIPING_SYSTEM",
        templateName: "Piping System",
        materialGroupCodes: ["962", "963", "965", "966", "979"],
        fields: [
            { fieldCode: "102", fieldOrder: 1, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "103", fieldOrder: 2, isMandatory: true, validationRuleType: "ALPHANUMERIC_CAPITAL", prefixValue: null, ruleDetail: "Huruf kapital dan angka", maxLength: null },
            { fieldCode: "104", fieldOrder: 3, isMandatory: false, validationRuleType: "MIXED_ALPHA_NUM_UNIT", prefixValue: null, ruleDetail: "Angka dan satuan ukuran", maxLength: null },
            { fieldCode: "116", fieldOrder: 4, isMandatory: false, validationRuleType: "MIXED_ALPHA_NUM_UNIT", prefixValue: null, ruleDetail: "Angka dan huruf", maxLength: null },
            { fieldCode: "105", fieldOrder: 5, isMandatory: false, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "117", fieldOrder: 6, isMandatory: false, validationRuleType: "ALPHANUMERIC_CAPITAL", prefixValue: null, ruleDetail: "Huruf kapital dan angka", maxLength: null },
        ],
    },
    {
        templateCode: "CHEMICAL_CONSUMABLES",
        templateName: "Chemical & Consumables",
        materialGroupCodes: ["912", "959", "929", "931", "922", "980", "985"],
        fields: [
            { fieldCode: "102", fieldOrder: 1, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "103", fieldOrder: 2, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "118", fieldOrder: 3, isMandatory: false, validationRuleType: "ALPHANUMERIC_CAPITAL", prefixValue: null, ruleDetail: "Huruf kapital dan angka", maxLength: null },
            { fieldCode: "119", fieldOrder: 4, isMandatory: false, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "104", fieldOrder: 5, isMandatory: false, validationRuleType: "MIXED_ALPHA_NUM_UNIT", prefixValue: null, ruleDetail: "Angka dan satuan", maxLength: null },
            { fieldCode: "107", fieldOrder: 6, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
        ],
    },
    {
        templateCode: "PACKAGING_PRODUCT_MATERIAL",
        templateName: "Packaging & Product Material",
        materialGroupCodes: ["958", "983", "972", "967", "948", "926", "949"],
        fields: [
            { fieldCode: "102", fieldOrder: 1, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "103", fieldOrder: 2, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "120", fieldOrder: 3, isMandatory: false, validationRuleType: "NUMERIC_ONLY", prefixValue: null, ruleDetail: "Angka", maxLength: null },
            { fieldCode: "105", fieldOrder: 4, isMandatory: false, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "121", fieldOrder: 5, isMandatory: false, validationRuleType: "NUMERIC_ONLY", prefixValue: null, ruleDetail: "Angka", maxLength: null },
            { fieldCode: "107", fieldOrder: 6, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
        ],
    },
    {
        templateCode: "CONSTRUCTION_CIVIL_MATERIAL",
        templateName: "Construction / Civil Material",
        materialGroupCodes: ["914", "976", "945"],
        fields: [
            { fieldCode: "102", fieldOrder: 1, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "103", fieldOrder: 2, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "119", fieldOrder: 3, isMandatory: false, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "120", fieldOrder: 4, isMandatory: false, validationRuleType: "NUMERIC_ONLY", prefixValue: null, ruleDetail: "Angka", maxLength: null },
            { fieldCode: "117", fieldOrder: 5, isMandatory: false, validationRuleType: "ALPHANUMERIC_CAPITAL", prefixValue: null, ruleDetail: "Huruf kapital dan angka", maxLength: null },
        ],
    },
    {
        templateCode: "OFFICE_GENERAL_SUPPLIES",
        templateName: "Office & General Supplies",
        materialGroupCodes: ["956", "974", "978", "930", "939"],
        fields: [
            { fieldCode: "102", fieldOrder: 1, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "103", fieldOrder: 2, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "118", fieldOrder: 3, isMandatory: false, validationRuleType: "ALPHANUMERIC_CAPITAL", prefixValue: null, ruleDetail: "Huruf kapital dan angka", maxLength: null },
            { fieldCode: "120", fieldOrder: 4, isMandatory: false, validationRuleType: "NUMERIC_ONLY", prefixValue: null, ruleDetail: "Angka", maxLength: null },
            { fieldCode: "107", fieldOrder: 5, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
        ],
    },
    {
        templateCode: "VEHICLE_TRANSPORTATION",
        templateName: "Vehicle & Transportation",
        materialGroupCodes: ["952"],
        fields: [
            { fieldCode: "122", fieldOrder: 1, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "107", fieldOrder: 2, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "106", fieldOrder: 3, isMandatory: false, validationRuleType: "ALPHANUMERIC_CAPITAL", prefixValue: null, ruleDetail: "Huruf kapital dan angka", maxLength: null },
            { fieldCode: "113", fieldOrder: 4, isMandatory: false, validationRuleType: "NUMERIC_ONLY", prefixValue: null, ruleDetail: "Angka", maxLength: null },
            { fieldCode: "123", fieldOrder: 5, isMandatory: false, validationRuleType: "NUMERIC_ONLY", prefixValue: null, ruleDetail: "Angka", maxLength: null },
        ],
    },
    {
        templateCode: "CAPITAL_EQUIPMENT",
        templateName: "Capital Equipment",
        materialGroupCodes: ["910"],
        fields: [
            { fieldCode: "102", fieldOrder: 1, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "103", fieldOrder: 2, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "113", fieldOrder: 3, isMandatory: false, validationRuleType: "NUMERIC_ONLY", prefixValue: null, ruleDetail: "Angka", maxLength: null },
            { fieldCode: "114", fieldOrder: 4, isMandatory: false, validationRuleType: "NUMERIC_ONLY", prefixValue: null, ruleDetail: "Angka", maxLength: null },
            { fieldCode: "106", fieldOrder: 5, isMandatory: false, validationRuleType: "ALPHANUMERIC_CAPITAL", prefixValue: null, ruleDetail: "Huruf kapital dan angka", maxLength: null },
            { fieldCode: "107", fieldOrder: 6, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
        ],
    },
    {
        templateCode: "GENERAL_MISCELLANEOUS",
        templateName: "General / Miscellaneous",
        materialGroupCodes: ["934", "951"],
        fields: [
            { fieldCode: "102", fieldOrder: 1, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "103", fieldOrder: 2, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
            { fieldCode: "118", fieldOrder: 3, isMandatory: false, validationRuleType: "ALPHANUMERIC_CAPITAL", prefixValue: null, ruleDetail: "Huruf kapital dan angka", maxLength: null },
            { fieldCode: "120", fieldOrder: 4, isMandatory: false, validationRuleType: "NUMERIC_ONLY", prefixValue: null, ruleDetail: "Angka", maxLength: null },
            { fieldCode: "107", fieldOrder: 5, isMandatory: true, validationRuleType: "CAPITAL_ONLY", prefixValue: null, ruleDetail: "Huruf kapital", maxLength: null },
        ],
    },
];

const TEMPLATE_FIELDS_BY_CODE = TEMPLATE_FIELDS.reduce((acc, field) => {
    acc[field.fieldCode] = field;
    return acc;
}, {});

module.exports = {
    REQUEST_FIELD_RULES,
    TEMPLATE_FIELDS,
    TEMPLATE_FIELDS_BY_CODE,
    TEMPLATE_DEFINITIONS,
};

